### ISSUE TITLE
Make it possible to configure package manager for views/frontend

### ISSUE THREAD

**Issue by matronator** [leafsphp/cli#13]
Currently it installs dependencies with `npm`, however I don't like using `npm` because it's slow and bloats the drive, so I use `pnpm` or `bun` and it would be great if I could configure Leaf CLI to use one of the other package managers instead of npm.

**Comment by mychidarko** [comment]
This is something we're looking at.

**Comment by mychidarko** [comment]
You can use `leaf view:` commands with --pm yarn, bun, pnpm eg:

```sh
leaf view:install vue --pm pnpm
```

We'll add further support for the UI later
