### ISSUE TITLE
Install leafs/cli on nvm

### ISSUE THREAD

**Issue by fonnets** [leafsphp/cli#5]
I use nvm to manage the versions of Node, with this configuration I cannot install leafs/cli globally on the version of node I am using with Composer already installed.

Are there any solutions?

Thanks

**Comment by mychidarko** [comment]
What's the exact error you're encountering?

**Comment by fonnets** [comment]
Hi,
no errors after launching the 'composer global require leafs/cli' command. But if I test the installation and run 'leaf' I get a 'command not found'. So I tried to add 'export PATH=$PATH:$HOME/.composer/vendor/bin' to my '.zshrc' file but it still doesn't work. I also tried with the my composer's global installation path, it doesn't work.
Thanks
Federico

**Comment by mychidarko** [comment]
Even after calling `source ~/.zshrc`?

**Comment by fonnets** [comment]
Now works! I didn't use the `source ~/.zshrc` command, the problem is that I insisted on running `leaf` in the same shell, opening a new terminal loads leaf correctly!
Maybe it might be helpful for fools like me to add this text in the guide: **relaunch your terminal and check leaf version** :)
Thanks
