### ISSUE TITLE
leafcli --watch: leaf-watcher not found

### ISSUE THREAD

**Issue by EnMaster** [leafsphp/cli#7]
OS: Ubuntu 22.10
PHP: 8.1.7
NPM: 8.18.0
LeafCLI: 2.7.0

LeafCLI installed from composer with
`composer global require leafs/cli`

When i star a project and serve with
`leaf serve --port 8080 --watch`
It returns 
> \* Leaf Watcher is required to enable monitoring. Install package?

But if i reply **Y**, it return this

> Installing leaf watcher...
> 
> changed 114 packages, and audited 115 packages in 1s
> 
> 18 packages are looking for funding
>   run \`npm fund\` for details
> 
> 4 moderate severity vulnerabilities
> 
> To address all issues (including breaking changes), run:
>   npm audit fix --force
> 
> Run \`npm audit\` for details.
> sh: 1: leaf-watcher: not found

Installing via npm manually using `npm install -g @leafphp/watcher` the installation go to end, but when i serve the project it return missing watcher.

**Comment by mychidarko** [comment]
Hi @EnMaster, after running `npm install -g @leafphp/watcher`, are you able to successfully run `leaf-watcher`?

**Comment by EnMaster** [comment]
Nope, It say leaf-watcher missing.

**Comment by mychidarko** [comment]
Oh okay, this seems to be a problem with npm, not leaf CLI specifically. The most likely cause of this is that your npm path isn't set correctly. You can check out these articles for some more context or help

- https://medium.com/@jagatjyoti.1si13cs040/npm-g-install-npm-package-not-working-as-desired-why-why-why-19795abf0b59
- https://stackoverflow.com/questions/15843199/globally-installed-npm-packages-not-working

**Comment by EnMaster** [comment]
Great! leaf-watcher now start!
