### ISSUE TITLE
Cannot create tests on Windows

### ISSUE THREAD

**Issue by aricooperdavis** [leafsphp/cli#8]
**Describe the bug**
Running `leaf test:setup` on windows powershell/cmd from within a leaf project gives the message:

```
> leaf test:setup
'.' is not recognized as an internal or external command,
operable program or batch file.
```

**To Reproduce**
1. Install leaf: `composer global require leafs/cli`
2. Create a new project: `leaf create test-project --api --v3`
3. Navigate to the new project: `cd .\test-api\`
4. Attempt to generate tests: `leaf test:setup`

**Expected behavior**
I would expect tests to be generated, but instead the error above is displayed.

**Additional context**
The path to the leaf project does not contain spaces. Running Leaf CLI v2.8.0 on Windows 10

**Comment by mychidarko** [comment]
Hi @aricooperdavis I'll check this out. In the mean time, you can run these commands instead:

```sh
leaf install alchemy

./vendor/bin/alchemy setup
./vendor/bin/alchemy run
```

**Comment by mychidarko** [comment]
@aricooperdavis, a new version of the Leaf CLI has been released. You can upgrade and see if this release fixes your issue

**Comment by mychidarko** [comment]
Hi @aricooperdavis, bumping this up. Has your issue been fixed now?

**Comment by aricooperdavis** [comment]
Now it opens the `leaf` file in the `test-project` directory in my default text editor!

**Comment by mychidarko** [comment]
😢 Can I see a screenshot of what's happening and one of your work directory?

**Comment by mychidarko** [comment]
@aricooperdavis, do you still have this issue?

**Comment by aricooperdavis** [comment]
I do not, I'm happy to close the issue it was solved by a reinstall :)

**Comment by mychidarko** [comment]
Awesome 😊
